- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart keepalived
  service: name=keepalived state=restarted

- name: restart rsyslogd
  service: name=rsyslog state=restarted
