---
# file: roles/java/tasks/main.yml

- name: "Create software directory"
  file:
    path: /opt/applications 
    state: directory
    mode: 0775

- debug: var=java_version

- name: "Check if java is already installed"
  shell: pkgutil --pkgs | grep -ie jdk 
  register: jdk

- debug: var=jdk.stdout_lines

- name: "Check if information above shows any result to see if java is already installed"
  pause: prompt="If java is already installed the playbook will fail - {{ jdk.stdout_lines }}" seconds=10

- name: "Download Java 6 from AWS"
  get_url:
    url: "{{ java6_mac_url }}" 
    dest: /opt/applications/java{{ java_version }}.dmg
  when: java_version == "6"

- name: "Download Java 7 from AWS"
  get_url:
    url: "{{ java7_mac_url }}" 
    dest: /opt/applications/java{{ java_version }}.dmg
  when: java_version == "7"

- name: "Download Java 8 from AWS"
  get_url:
    url: "{{ java8_mac_url }}" 
    dest: /opt/applications/java{{ java_version }}.dmg
  when: java_version == "8"

- name: "Mount Java {{ java_version }} image"
  shell: hdiutil attach /opt/applications/java{{ java_version }}.dmg

- name: "Install Java{{ java_version }}"
  shell: installer -package /Volumes/JDK*/*.pkg -target /

- name: "Unmount {{ java_version }} image"
  shell: hdiutil detach /Volumes/JDK*