---
# file: roles/java/tasks/main.yml

- name: Create software directory
  file: path=/tmp/software state=directory 

- debug: var=java_version

- name: Download Java 6 from AWS
  get_url: 
     url: "{{ java6_url }}"
     dest: /tmp/software/java{{java_version}}.tar.gz
  when: java_version == "6"

- name: Download Java 7 from AWS
  get_url:
     url: "{{ java7_url }}"
     dest: /tmp/software/java{{java_version}}.tar.gz
  when: java_version == "7"

- name: Download Java 8 from AWS
  get_url: 
     url: "{{ java6_url }}"
     dest: /tmp/software/java{{java_version}}.tar.gz
  when: java_version == "8"

- name: Get java name in order to create /usr/java symlink
  shell: tar -tf /tmp/software/java{{java_version}}.tar.gz | cut -d "/" -f1 | uniq
  register: java_name

- name: Check if path exists
  stat: path=/usr/{{ java_name.stdout }}
  register: check_path

- name: Extract Java into /usr/
  unarchive: src=/tmp/software/java{{java_version}}.tar.gz dest=/usr/ copy=no
  when: check_path.stat.exists == false

- name: Change permisions for /usr/ java version
  file: path=/usr/{{ java_name.stdout }} owner=root group=root recurse=yes

- name: Create symlink /usr/java pointing to this new java version
  file: dest=/usr/java src=/usr/{{ java_name.stdout }} state=link

- name: Correct java version selected
  alternatives: name=java link=/usr/bin/java path=/usr/{{java_name.stdout}}/bin/java

- name: Correct javac version selected
  alternatives: name=javac link=/usr/bin/javac path=/usr/{{java_name.stdout}}/bin/javac
