---
# file: roles/java/tasks/main.yml

- name: Create software directory
  win_file: path=C:\\applications state=directory 

- debug: var=java_version

- name: Check to see if java is installed
  win_stat: path='C:\applications\java{{ java_version }}.exe'
  register: java_installed

- debug: var=java_installed

- name: Download Java 7 from AWS
  win_get_url:
     url: "{{ java7_win_url }}"
     dest: C:\\applications\java{{ java_version }}.exe
     force: yes
  when: java_version == "7"
  ignore_errors: yes

- name: Download Java 8 from AWS
  win_get_url:
     url: "{{ java8_win_url }}"
     dest: C:\\applications\java{{ java_version }}.exe
     force: yes
  when: java_version == "8"
  ignore_errors: yes

- name: Install java{{ java_version }}
  raw: 'C:\\applications\java{{ java_version }}.exe /s /L C:\\applications\java{{ java_version }}install.log'
  when: not java_installed.stat.exists