---

- name: Install python-pycurl
  yum: name=python-pycurl state=installed

- name: Import jenkins key
  rpm_key:
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

#- name: Log in to Jenkins CLI if auth config is available
  # OK to ignore errors as it won't work before Jenkins is installed
#  ignore_errors: yes
# command: >
#    {{ jenkins_cli_cmd }} login --username {{ jenkins_admin_user }} --password {{ jenkins_admin_password }}
#  when: jenkins_admin_user is defined and jenkins_admin_password is defined

- name: Install dependencies
  yum: name={{ item }} state=installed
  with_items: "{{ jenkins.redhat.dependencies }}"

- name: Install Jenkins
  yum: name=jenkins state=latest
  register: jenkins_install

- name: Ensure jenkins is running
  service:
    name: jenkins
    state: started

- name: Start jenkins on boot
  shell: chkconfig jenkins on

- include: config.yml
- include: cli.yml
- include: plugins.yml