---
jenkins_dest: /opt/jenkins
jenkins_lib: /var/lib/jenkins
jenkins:
  redhat:
    dependencies:
      - 'java'
      - 'git'
      - 'curl'
  cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar' # Jenkins CLI destination
  cli_key: '{{ jenkins_lib }}secret.key'
  updates_dest: '{{ jenkins_dest }}/updates_jenkins.json' # Jenkins updates file
jenkins_api_url: "http://localhost:{{ jenkins_port }}{{ jenkins_prefix }}"
jenkins_cli_cmd: "java -jar {{ jenkins.cli_dest }} -s {{ jenkins_api_url }}"